#!/usr/bin/env bash
#
# Phosphor Phase 3 — YubiKey tooling for signing-key custody
#
#   sudo bash scripts/host-setup-phase3-yubikey.sh
#
# Installs the smartcard/PIV tooling used to gate the signing-key passphrase
# behind a physical YubiKey, per docs/PHASE-3-KEY-MANAGEMENT-DESIGN.md §5.
#
# Idempotent — safe to re-run. Installs nothing twice, and does not touch any
# key material. No keys are generated by this script.
#
set -o errexit -o nounset -o pipefail

# yubico-piv-tool  PIV key generation + the passphrase seal/unseal operations
# yubikey-manager  ykman: inspect and provision the token
# yubikey-personalization  ykchalresp: fallback gating via HMAC challenge-response
# opensc           pkcs11-tool + opensc-pkcs11.so (the PKCS#11 module)
# pcscd            smartcard daemon; PIV operations go through it
# pcsc-tools       pcsc_scan, for confirming the token is reachable
# libfido2-1       FIDO2 hmac-secret; alternative gating primitive
PACKAGES=(
  yubico-piv-tool
  yubikey-manager
  yubikey-personalization
  opensc
  pcscd
  pcsc-tools
  libfido2-1
)

echo "==> Phosphor Phase 3 — YubiKey tooling"
echo

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: this script must run as root." >&2
  echo "       sudo bash $0" >&2
  exit 1
fi

# ---------------------------------------------------------------- pre-flight
echo "==> Checking the token is attached"
if lsusb 2>/dev/null | grep -q '1050:'; then
  lsusb 2>/dev/null | grep '1050:' | sed 's/^/    /'
else
  echo "    WARNING: no Yubico device on USB."
  echo "    Install can proceed; plug the token in before provisioning it."
fi
echo

# ------------------------------------------------------------ install phase
echo "==> Working out what needs installing"
to_install=()
for pkg in "${PACKAGES[@]}"; do
  if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q 'install ok installed'; then
    printf '    already installed: %s\n' "$pkg"
  else
    printf '    to install:        %s\n' "$pkg"
    to_install+=("$pkg")
  fi
done
echo

if [[ ${#to_install[@]} -gt 0 ]]; then
  echo "==> Installing ${#to_install[@]} package(s)"
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${to_install[@]}"
else
  echo "==> Nothing to install"
fi
echo

# ------------------------------------------------------------- service phase
# PIV operations need the smartcard daemon. Ubuntu ships pcscd socket-activated,
# so enable the socket as well as the service — without the socket, the first
# connection after boot can fail with "service not available".
echo "==> Enabling pcscd (needed for every PIV operation)"
systemctl enable --now pcscd.service 2>/dev/null || true
systemctl enable --now pcscd.socket  2>/dev/null || true
sleep 1
if systemctl is-active --quiet pcscd.service || systemctl is-active --quiet pcscd.socket; then
  echo "    pcscd: active"
else
  echo "    WARNING: pcscd is not active — PIV operations will fail."
  echo "    Check: systemctl status pcscd"
fi
echo

# The CCID group rule in 92-libccid.rules (GROUP="pcscd") is applied by udev
# only when a device appears. Installing this tooling while the token is already
# plugged in leaves the existing node owned by root:root, and pcscd then fails
# with "Can't libusb_open(1/N): LIBUSB_ERROR_ACCESS" — which shows up as
# "ykman piv info: Failed to connect to YubiKey" and "No smart card readers
# found". Re-apply the rules here so a fresh run does not hit that.
echo "==> Re-applying udev rules to the attached token"
udevadm control --reload-rules 2>/dev/null || true
udevadm trigger --subsystem-match=usb --action=add 2>/dev/null || true
sleep 2

node=""
for d in /dev/bus/usb/*/*; do
  [[ -c $d ]] || continue
  if udevadm info -q property -n "$d" 2>/dev/null | grep -q '^ID_VENDOR_ID=1050$'; then
    node="$d"
    break
  fi
done

if [[ -n $node ]]; then
  grp=$(ls -l "$node" | awk '{print $4}')
  echo "    $(ls -l "$node" | awk '{print $1, $3, $4}')  ($node)"
  if [[ $grp == pcscd ]]; then
    echo "    group is 'pcscd' — correct, pcscd can open the CCID interface"
  else
    echo "    WARNING: group is '$grp', expected 'pcscd' — PIV will not work."
    echo "    Unplug and replug the token, then re-run this script."
    echo "    (or run: sudo bash scripts/host-fix-yubikey-ccid.sh)"
  fi
else
  echo "    no Yubico device attached — skipping"
  echo "    plug the token in before provisioning it"
fi
echo

# ------------------------------------------------------------ verify phase
echo "==> Verifying the tools"
for bin in ykman yubico-piv-tool pkcs11-tool pcsc_scan ykchalresp; do
  if command -v "$bin" >/dev/null 2>&1; then
    printf '    %-16s %s\n' "$bin" "$(command -v "$bin")"
  else
    printf '    %-16s MISSING\n' "$bin"
  fi
done
echo

echo "==> Locating the PKCS#11 module"
mod=""
for cand in /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so \
            /usr/lib/opensc-pkcs11.so \
            /usr/lib64/opensc-pkcs11.so; do
  [[ -f $cand ]] && mod="$cand" && break
done
if [[ -n $mod ]]; then
  echo "    $mod"
else
  echo "    WARNING: opensc-pkcs11.so not found — pkcs11-tool will not work."
fi
echo

echo "==> Token report"
if command -v ykman >/dev/null 2>&1 && lsusb 2>/dev/null | grep -q '1050:'; then
  ykman info 2>&1 | sed 's/^/    /' || echo "    (ykman could not read the token)"
else
  echo "    skipped — token not attached, or ykman unavailable"
fi
echo

# ------------------------------------------------------------------ next up
cat <<'EOF'
==> Done.

Next step is to provision the token — this is where your PIN is used, and it is
typed at the prompt by you, never passed to or handled by the agent:

    bash ~/projects/Phosphor/scripts/keys-yubikey-provision.sh

That generates the passphrase-wrapping key inside the token's PIV slot 9d and
round-trips a test secret to prove the seal/unseal path works. Only once that
succeeds should the signing keys themselves be generated — otherwise the
passphrase exists unprotected between generation and sealing.

To undo:  sudo apt-get remove --purge yubico-piv-tool yubikey-manager \
            yubikey-personalization opensc pcsc-tools
          (pcscd and libfido2-1 are common system packages; leave them.)
EOF
